export enum AuthActionTypes {
  REGITSER = 'REGISTER',
  LOGIN = 'LOGIN',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  AUTH_REQUEST_FAILURE = 'AUTH_REQUEST_FAILURE',
  GET_PROFILE = 'GET_PROFILE',
  GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS',
  LOGOUT = 'LOGOUT'
}
